version: '3'

networks:
  lan:
    name: de-rbearthgaze-network
    external: true

services:
  master:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-master
    hostname: spark-master
    ports:
      - '8080:8080'
      - '7077:7077'
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_USER: spark
    networks:
      - lan

  worker-1:
    image: docker.io/bitnami/spark:3.5
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://master:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
      SPARK_USER: spark
    networks:
      - lan
